version: '3.7'
services:
  poteriashki_db:
    image: postgres:14
    container_name: poteriashki_db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./.data/db:/var/lib/postgresql/data

  poteriashki:
    build:
      context: .
    depends_on:
      - postgres
    container_name: poteriashki
    env_file:
      - .env
    restart: unless-stopped
