version: '3.7'
services:
  poteriashki_db:
    image: postgres:15.1
    container_name: poteriashki_db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./poteriashki_db:/var/lib/postgresql/data

  poteriashki:
    build:
      context: .
    depends_on:
      - poteriashki_db
    container_name: poteriashki
    env_file:
      - .env
    restart: unless-stopped

