version: '3.7'
services:
  notifications_db:
    image: postgres:14
    container_name: notifications_db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
